types:
  - type: feat
    description: A new feature
  - type: fix
    description: A bug fix
  - type: docs
    description: Documentation only changes
  - type: style
    description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
  - type: refactor
    description: A code change that neither fixes a bug nor adds a feature
  - type: perf
    description: A code change that improves performance
  - type: test
    description: Adding missing tests or correcting existing tests
  - type: build
    description: Changes that affect the build system or external dependencies
  - type: ci
    description: Changes to our CI configuration files and scripts
  - type: chore
    description: Other changes that don't modify src or test files
  - type: revert
    description: Reverts a previous commit

